### PR TITLE
FEAT: add SharedAccessKey as authentication option in the API template

### PR DESCRIPTION
**Pull request by stijnmoreels**
Relates to #10

### CODE REVIEW

**Comment by tomkerkhove** [comment]
@stijnmoreels 	Would be good if we prio packaging before adding any new features.

Would allow us to pull in preview packages and try them to see if this works, if that's ok for you?

**Comment by tomkerkhove** [comment]
Would you mind resolving these please @stijnmoreels ?

**Comment by stijnmoreels** [comment]
Ok, so can I leave this PR open till we have all the minimum work done? Thanks.

PS. I agree to wait with this 🤸

**Comment by tomkerkhove** [comment]
For me it's ok to merge this one as it looks ok but before adding more features in the template I'd suggest looking at CI + preview packages first.

**Pull request merged**
