### PR TITLE
FEAT: add Open API security definitions as project option

### PR DESCRIPTION
**Pull request by stijnmoreels**
A new project option is introduced to include the security responses to
authorized API endpoints.
This feature required to have an additional controller to be tested
correctly, which means the `WebApiProject` was slightly altered to have
the possibility to add fixture files after the project is created but
before it's started.

### CODE REVIEW

**Comment by tomkerkhove** [comment]
Is this to add [OAuth security definition to API operations](https://webapi.arcus-azure.net/features/openapi/security-definitions)?

If so, I'm not sure if this should be part of the template in my opinion as a very little userbase will need this 🤔 

What do you think @MassimoC?

**Comment by stijnmoreels** [comment]
Hmm, if it's a small userbase, I'm wondering why it's in Arcus web API actually.

**Comment by tomkerkhove** [comment]
For those who need it ;)

The aim for this template is to provide a good starting point with the feature that have to be there for all APIs where in this case it's more for folks who can use this and still pull it in themselves

**Comment by stijnmoreels** [comment]
> For those who need it ;)
> 
> The aim for this template is to provide a good starting point with the feature that have to be there for all APIs where in this case it's more for folks who can use this and still pull it in themselves

Ok, I'll close this PR, then?

**Comment by tomkerkhove** [comment]
I'd suggest to do so if that's ok. Typically we'd first discuss new additions to the template before adding them to avoid this, sorry about that.

**Pull request closed without merging**
