### PR TITLE
Fix CI triggers for PRs & branch-based builds

### PR DESCRIPTION
**Pull request by tomkerkhove**
Fix CI triggers for PRs & branch-based builds given they are not kicking in for PRs.

### CODE REVIEW

**Comment by tomkerkhove** [comment]
Here we go, now they are working.

**Comment by stijnmoreels** [comment]
> Here we go, now they are working.

? What changed? I though they already ran? Like prev PR's they already ran.

**Comment by tomkerkhove** [comment]
But you are saying that it used to work for changes to the CI YAML, is that correct? :thinking:

**Comment by stijnmoreels** [comment]
> But you are saying that it used to work for changes to the CI YAML, is that correct? 🤔

Yeah, like this one: https://github.com/arcus-azure/arcus.templates/pull/53

**Comment by tomkerkhove** [comment]
Hm then it might just be because of the merge conflicts in #55 🤔

**Comment by tomkerkhove** [comment]
It did the trick! (TIL)

Abandoning. Thank you @stijnmoreels !

**Pull request closed without merging**
