### PR TITLE
FEAT: add console logging as default logger

### PR DESCRIPTION
**Pull request by stijnmoreels**
Relates to #10

### CODE REVIEW

**Comment by stijnmoreels** [comment]
We could register a logger that discards the log messages. That way we don't take dependency on the log console NuGet package?

**Comment by tomkerkhove** [comment]
@stijnmoreels 	What do you mean? Can you give an example please?

_PS: I have no issue with the dependency that was added to be honest._

**Comment by stijnmoreels** [comment]
> @stijnmoreels What do you mean? Can you give an example please?
> 
> _PS: I have no issue with the dependency that was added to be honest._

Just a thought: if we setup the logging system for the API but register a provider that discards the log messages (ex. `NullLogger`) than we don't need any extra dependency and yet have shown the user to provide a logging system.

**Comment by tomkerkhove** [comment]
That is correct but the idea is that the template provides a easy to setup and good to get started template with the minimal requirements so we should have console logging at least!

**Pull request merged**
